server:
  port: 8089
  servlet:
    context-path: /


#配置mysql的连接信息（配置数据源）
spring:
  datasource:
    username: root
    password: wsttzisme
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlyk?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    hikari:
#      最大连接数:默认为10
      maximum-pool-size: 30
#      最小空闲连接数,默认为10
      minimum-idle: 30
#      等待连接池分配连接的最大时长,超过该时长还没有可用连接则发生超时异常(毫秒)
      connection-timeout: 5000
#      空闲连接的最大时长,空闲多久就被释放回归,设置为0不让连接回收
      idle-timeout: 0
#      一个连接的最大生命时间,超过改时间还未使用就回收掉(毫秒),最好不超过8小时
      max-lifetime: 18000000

  #设置jackson返回json数据时，时区和格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


  #配置redis的连接信息
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: wsttzisme
      database: 0

#指定mapper.xml文件的位置(xml和mapper不在一个地方的时候需要指定一下位置)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #在控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#定义定时任务的调度时间
project:
  task:
#    cron: '*/3 * * * * *'
    cron: '* */5 * * * *'
    delay: 180000